# Generated by Django 4.1.4 on 2022-12-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexmoney', '0002_rename_todo_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phoneNumber',
            field=models.IntegerField(blank=True),
        ),
    ]
