# Generated by Django 4.1.4 on 2022-12-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexmoney', '0003_alter_userdetails_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
    ]
