# Generated by Django 4.1.4 on 2023-03-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexmoney', '0006_alter_blog_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
