# Generated by Django 4.1.4 on 2023-04-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexmoney', '0009_profile_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
