# Generated by Django 4.1.4 on 2023-05-16 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flexmoney', '0012_alter_board_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('due', models.DateTimeField(blank=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='flexmoney.board')),
                ('members', models.ManyToManyField(blank=True, related_name='card_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
