# Generated by Django 4.1.4 on 2023-05-16 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flexmoney', '0014_alter_card_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='due',
        ),
        migrations.RemoveField(
            model_name='card',
            name='members',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('due', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='flexmoney.card')),
                ('members', models.ManyToManyField(blank=True, related_name='task_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
