# Generated by Django 4.1.4 on 2023-05-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexmoney', '0015_remove_card_due_remove_card_members_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
